### ISSUE TITLE
Plans to support Wagtail v2?

### ISSUE THREAD

**Issue by ugotsoul** [torchbox/wagtail-experiments#16]
I read the library works with Wagtail 1.7, but I'm hoping to use this framework once we upgrade our site to Wagtail 2.0. Also, by asking this question, I'm also volunteering to work on this issue with some guidance from more experienced wagtail / django / python devs (JS dev here) :D

**Comment by nsomaru** [comment]
Willing to volunteer here too. Complete wagtail noob.

**Comment by jessemenn** [comment]
I've started on this [over here](https://github.com/jessemenn/wagtail-experiments), but don't know what else is/may be needed. I believe it's working on my wagtail 2.1 and django 2.0, but don't know about other versions that may still be supported.

**Comment by ugotsoul** [comment]
FYI: https://github.com/wagtail/wagtail/issues/529#issuecomment-264844913

> It's worth bearing in mind that the wagtail-experiments module currently relies on the assumption that a draft edit to an unpublished page will not update the main pages table... if we change this behaviour, it will need to be documented accordingly (and to make wagtail-experiments work, we'd probably have to introduce the concept of additional page states besides 'published' which keep the page record frozen at a particular point).

This behavior is added in 2017, in this PR: https://github.com/wagtail/wagtail/pull/3285

It seems like wagtail-experiments does copy content from alternative variations to the  main pages table here: https://github.com/torchbox/wagtail-experiments/blob/master/experiments/models.py#L55

**Comment by gasman** [comment]
PR now created to add Wagtail 2.x / Django 2.x support: #17

@ugotsoul As far as I'm aware, https://github.com/wagtail/wagtail/pull/3285 avoids making the breaking change that I was concerned about in https://github.com/wagtail/wagtail/issues/529#issuecomment-264844913 - saving as draft only modifies the `draft_title` and `latest_revision_created_at` fields, so that information won't 'leak' into the page as displayed to the user.

**Comment by gasman** [comment]
Implemented in #17
